[build]
  base = "frontend/"
  command = "npm run build"
  publish = "build/"

[build.environment]
  REACT_APP_API_URL = "https://adaptive-curriculum-engine.onrender.com/api"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://adaptive-curriculum-engine.onrender.com; font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com; img-src 'self' data: https:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200