[build]
  base = "frontend/"
  command = "npm run build"
  publish = "build/"

[build.environment]
  REACT_APP_API_URL = "https://your-backend-url.onrender.com/api"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200